apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: {{ PROJECT_ENVIRONMENT }}-mongo
  name: {{ PROJECT_ENVIRONMENT }}-mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ PROJECT_ENVIRONMENT }}-mongo
    spec:
      containers:
      - image: mongo
        name: {{ PROJECT_ENVIRONMENT }}-mongo
        ports:
        - name: {{ PROJECT_ENVIRONMENT }}-mongo
          containerPort: {{ MONGO_PORT }}
          # hostPort: {{ MONGO_PORT }}
        volumeMounts:
            - name: {{ MONGO_VOLUME }}
              mountPath: /data/db
      volumes:
        - name: {{ MONGO_VOLUME }}
          gcePersistentDisk:
            pdName: {{ MONGO_DISK }}
            fsType: ext4
