apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ PROJECT_NAME }}-mongo
  name: {{ PROJECT_NAME }}-mongo
spec:
  ports:
    - port: {{ MONGO_PORT }}
      targetPort: {{ MONGO_PORT }}
  selector:
    name: {{ PROJECT_NAME }}-mongo