---
kind: Pod
apiVersion: v1
metadata:
  name: gnomad-load
  labels:
    state: loading
spec:
  restartPolicy: Never
  containers:
  - name: gnomad-load
    image: gcr.io/exac-gnomad/gnomadload
    env:
    - name: DEPLOYMENT_ENV
      value: production
    - name: LOAD_DB_PARALLEL_PROCESSES_NUMB
      value: '32'
    - name: EXOMES_SINGLE_VCF
      value: {{ EXOMES_SINGLE_VCF }}
    - name: GENOMES_VCF_GLOB
      value: {{ GENOMES_VCF_GLOB }}
    - name: EXOMES_SINGLE_VCF_TEST
      value: {{ EXOMES_SINGLE_VCF_TEST }}
    - name: GENOMES_VCF_GLOB_TEST
      value: {{ GENOMES_VCF_GLOB_TEST }}
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
    imagePullPolicy: Always
