---
kind: Pod
apiVersion: v1
metadata:
  name: {{ PROJECT_ENVIRONMENT }}-precalculate
  labels:
    state: loading
spec:
  restartPolicy: Never
  containers:
  - name: {{ PROJECT_ENVIRONMENT }}-precalculate
    image: gcr.io/{{ GCLOUD_PROJECT }}/{{ PROJECT_NAME }}precalculate
    imagePullPolicy: Always
