---
kind: Pod
apiVersion: v1
metadata:
  name: {{ PROJECT_ENVIRONMENT }}-load
  labels:
    state: loading
spec:
  restartPolicy: Never
  containers:
  - name: {{ PROJECT_ENVIRONMENT }}-load
    image: gcr.io/{{ GCLOUD_PROJECT }}/{{ PROJECT_NAME }}load:{{ BROWSER_VERSION }}-{{ DATA_VERSION }}-{{ BUILD_TIME }}
    env:
    - name: DEPLOYMENT_ENV
      value: 'production'
    - name: MONGO_HOST
      value: {{ MONGO_HOST }}
    - name: MONGO_PORT
      value: '{{ MONGO_PORT }}'
    - name: LOAD_DB_PARALLEL_PROCESSES_NUMB
      value: {{ LOAD_DB_PARALLEL_PROCESSES_NUMB }}
    - name: EXOMES_SINGLE_VCF
      value: {{ EXOMES_SINGLE_VCF }}
    - name: GENOMES_VCF_GLOB
      value: {{ GENOMES_VCF_GLOB }}
    - name: EXOMES_SINGLE_VCF_TEST
      value: {{ EXOMES_SINGLE_VCF_TEST }}
    - name: GENOMES_VCF_GLOB_TEST
      value: {{ GENOMES_VCF_GLOB_TEST }}
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
    imagePullPolicy: Always
