---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ PROJECT_ENVIRONMENT }}-serve
  labels:
    state: serving
spec:
  replicas: {{ SERVER_REPLICAS }}
  selector:
    matchLabels:
      name: {{ PROJECT_ENVIRONMENT}}-app
  template:
    metadata:
      labels:
        name: {{ PROJECT_ENVIRONMENT }}-app
    spec:
      volumes:
      - name: {{ READVIZ_VOLUME }}
        gcePersistentDisk:
          pdName: {{ READVIZ_DISK }}
          fsType: ext4
          readOnly: true
      containers:
      - name: {{ PROJECT_ENVIRONMENT }}-serve
        image: gcr.io/{{ GCLOUD_PROJECT }}/{{ PROJECT_NAME }}serve:{{ BROWSER_VERSION }}-{{ DATA_VERSION }}
        env:
        - name: DEPLOYMENT_ENV
          value: production
        - name: MONGO_HOST
          value: {{ MONGO_HOST }}
        - name: MONGO_PORT
          value: '{{ MONGO_PORT }}'
        - name: EXOMES_SINGLE_VCF
          value: {{ EXOMES_SINGLE_VCF }}
        - name: GENOMES_VCF_GLOB
          value: {{ GENOMES_VCF_GLOB }}
        - name: EXOMES_SINGLE_VCF_TEST
          value: {{ EXOMES_SINGLE_VCF_TEST }}
        - name: GENOMES_VCF_GLOB_TEST
          value: {{ GENOMES_VCF_GLOB_TEST }}
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: {{ READVIZ_VOLUME }}
          mountPath: /var/data/readviz
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
