apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: gnomad-mongo-2
  name: gnomad-mongo-controller-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gnomad-mongo-2
    spec:
      containers:
      - image: mongo
        name: gnomad-mongo-2
        ports:
        - name: gnomad-mongo-2
          containerPort: 27017
          # hostPort: 27017
        volumeMounts:
            - name: gnomad-mongo-persistent-storage-2
              mountPath: /data/db
      volumes:
        - name: gnomad-mongo-persistent-storage-2
          gcePersistentDisk:
            pdName: gnomad-mongo-disk-2
            fsType: ext4
